name: main
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: install
        run: |
          sudo add-apt-repository ppa:fenics-packages/fenics
          sudo apt-get update
          sudo apt-get -y dist-upgrade
          sudo apt-get -y install fenics
      - name: run script
        run: |
          python3 demo_cahn-hilliard.py
