name: milk-crown
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  script:
    runs-on: ubuntu-20.04
    steps:
    - name: install
      run: |
        sudo add-apt-repository ppa:fenics-packages/fenics
        sudo apt-get update
        sudo apt-get -y install fenics
        sudo apt-get -y dist-upgrade
    - name: setup ssh
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: run script
      run: |
        python3 demo_cahn-hilliard.py
